const models={
 ipad:{name:'無印 iPad',chip:'A16',sizes:'11インチ',storage:'128 / 256 / 512GB',pencil:'Apple Pencil（USB-C）／第1世代',keyboard:'Magic Keyboard Folio',display:'Liquid Retina・sRGB',for:'動画・学習・Web・普段使い',tone:'#2563eb'},
 air:{name:'iPad Air',chip:'M4',sizes:'11 / 13インチ',storage:'128 / 256 / 512GB / 1TB',pencil:'Apple Pencil Pro／USB-C',keyboard:'iPad Air用Magic Keyboard',display:'Liquid Retina・P3・フルラミネーション',for:'仕事・写真編集・趣味・長く快適に',tone:'#059669'},
 pro:{name:'iPad Pro',chip:'M5',sizes:'11 / 13インチ',storage:'256 / 512GB / 1 / 2TB',pencil:'Apple Pencil Pro／USB-C',keyboard:'iPad Pro用Magic Keyboard',display:'Ultra Retina XDR・ProMotion',for:'動画編集・イラスト・高負荷作業',tone:'#7c3aed'}
};
const pages={
 home:{sub:'無印・Air・Proを、接客で迷わず選ぶ',render:home},compare:{sub:'3モデルの違いを一目で比較',render:compare},chip:{sub:'A16・M4・M5の違い',render:chip},capacity:{sub:'容量選びをわかりやすく',render:capacity},accessory:{sub:'Apple Pencil・キーボード対応',render:accessory},diagnosis:{sub:'質問に答えておすすめを診断',render:diagnosis},talk:{sub:'そのまま使える提案トーク',render:talk},faq:{sub:'よくある質問をすぐ確認',render:faq},learn:{sub:'ミニテストで知識を定着',render:learn}
};
let route='home', historyStack=[];
const content=document.querySelector('#content'),backBtn=document.querySelector('#backBtn');
function go(r,push=true){if(push&&route!==r)historyStack.push(route);route=r;document.querySelector('#pageSub').textContent=pages[r].sub;content.innerHTML=pages[r].render();backBtn.classList.toggle('hidden',r==='home');document.querySelectorAll('.bottomNav button').forEach(b=>b.classList.toggle('active',b.dataset.route===r));window.scrollTo({top:0,behavior:'smooth'});afterRender(r)}
function afterRender(r){if(r==='diagnosis')initDiagnosis();if(r==='learn')initQuiz()}
document.querySelectorAll('.bottomNav button').forEach(b=>b.onclick=()=>go(b.dataset.route));backBtn.onclick=()=>{const prev=historyStack.pop()||'home';go(prev,false)};
function home(){return `<section class="hero"><div><span class="pill">✨ VISUAL UPDATE</span><h1>選べる。説明できる。<br>提案に自信がつく。</h1><p>無印 iPad・iPad Air・iPad Proの違いを、比較 → 診断 → 提案までひとつにつないだ接客サポート版。</p></div><div class="heroArt imageArt"><img src="ipad-lineup.svg" alt="無印iPad、iPad Air、iPad Proのイメージ"></div></section><div class="grid">
${tile('⚖️','3モデル比較','無印・Air・Proを横並びで確認','compare','blue')}${tile('🧠','チップ比較','A16・M4・M5を用途で理解','chip','green')}${tile('🎯','お客様診断','質問に答えておすすめを絞る','diagnosis','purple')}${tile('💾','容量の選び方','128GBから2TBまで整理','capacity','orange')}${tile('✏️','Pencil・キーボード','対応アクセサリを確認','accessory','pink')}${tile('💬','接客トーク','提案理由までそのまま使える','talk','cyan')}${tile('❓','FAQ','よく聞かれる質問に即答','faq','blue')}${tile('🎓','ミニテスト','知識を5問でチェック','learn','green')}${tile('⭐','お気に入り','よく使うページは今後拡張','home','purple')}</div>`}
function tile(icon,title,p,rt,cls){return `<button class="tile ${cls}" onclick="go('${rt}')"><div class="icon">${icon}</div><h3>${title}</h3><p>${p}</p></button>`}
function modelCards(){return `<div class="modelGrid">${Object.entries(models).map(([k,m])=>`<article class="card model ${k}"><span class="pill">${m.sizes}</span><h2>${m.name}</h2><div class="chip">${m.chip}</div><ul><li>${m.for}</li><li>${m.storage}</li><li>${m.pencil}</li></ul></article>`).join('')}</div>`}
function compare(){return `<img class="pageVisual" src="ipad-lineup.svg" alt="無印iPad、iPad Air、iPad Proの比較イメージ"><div class="sectionTitle">⚖️ ひとこと比較</div>${modelCards()}<div class="sectionTitle">📊 詳しく比較</div><div class="tableWrap"><table class="compareTable"><thead><tr><th>項目</th><th>無印 iPad</th><th>iPad Air</th><th>iPad Pro</th></tr></thead><tbody>
${row('チップ','A16','M4','M5')}${row('サイズ','11インチ','11 / 13インチ','11 / 13インチ')}${row('容量','128〜512GB','128GB〜1TB','256GB〜2TB')}${row('画面','Liquid Retina','Liquid Retina + P3','Ultra Retina XDR + ProMotion')}${row('Pencil','USB-C / 第1世代','Pro / USB-C','Pro / USB-C')}${row('キーボード','Magic Keyboard Folio','Air用Magic Keyboard','Pro用Magic Keyboard')}${row('おすすめ','普段使い・学習','万能・仕事・趣味','制作・高負荷作業')}</tbody></table></div><p class="note">※価格は変動するためアプリ内では固定表示せず、店頭の最新価格をご確認ください。</p>`}
function row(a,b,c,d){return `<tr><td>${a}</td><td>${b}</td><td class="good">${c}</td><td class="best">${d}</td></tr>`}
function chip(){return `<img class="pageVisual" src="chips.svg" alt="A16・M4・M5チップ比較図"><div class="sectionTitle">🧠 チップは「できる／できない」より“余裕”で考える</div>${modelCards()}<div class="card"><div class="tableWrap"><table class="compareTable"><thead><tr><th>使い方</th><th>A16</th><th>M4</th><th>M5</th></tr></thead><tbody>${row('動画・Web・学習','◎ 十分','◎ 余裕','◎ 余裕大')}${row('複数アプリ','○','◎','◎')}${row('写真編集','○','◎','◎')}${row('動画編集・制作','△〜○','◎','◎◎')}${row('長く高負荷で使う','△','◎','◎◎')}</tbody></table></div><p class="note">接客ポイント：単純に「M5が一番速い」で終わらず、用途に対して必要な余裕がどこまでかを確認。</p></div>`}
function capacity(){return `<img class="pageVisual" src="capacity.svg" alt="iPadストレージ容量の比較図"><div class="sectionTitle">💾 容量は「今」より「使い方が増えた時」で選ぶ</div><div class="grid">${cap('128GB','動画視聴・Web・学習が中心','端末に写真や動画を大量保存しない方向け','blue')}${cap('256GB','迷った時の基準','写真・アプリ・ゲームもある程度安心','green')}${cap('512GB','保存が多い','動画・写真・編集データを持ち歩く','purple')}${cap('1TB〜2TB','本格制作','大容量の素材・制作データを端末に置く','orange')}</div><div class="card"><b>接客で聞く3点</b><div class="reasonList"><div class="reason">① 写真・動画は端末にたくさん保存する？</div><div class="reason">② ゲームや大容量アプリを多く入れる？</div><div class="reason">③ 3〜5年使った時に容量不足が心配？</div></div></div>`}
function cap(a,b,c,cl){return `<article class="tile ${cl}"><div class="icon">💽</div><h3>${a}</h3><p><b>${b}</b><br>${c}</p></article>`}
function accessory(){return `<img class="pageVisual" src="accessories.svg" alt="Apple Pencilとキーボードのイメージ"><div class="sectionTitle">✏️ Apple Pencil・キーボード</div><div class="tableWrap"><table class="compareTable"><thead><tr><th>モデル</th><th>Apple Pencil</th><th>キーボード</th><th>向く使い方</th></tr></thead><tbody>${row('無印 iPad','USB-C / 第1世代','Magic Keyboard Folio','メモ・学習・入力')}${row('iPad Air','Pencil Pro / USB-C','Air用Magic Keyboard','仕事・趣味・描画')}${row('iPad Pro','Pencil Pro / USB-C','Pro用Magic Keyboard','本格制作・高精度作業')}</tbody></table></div><div class="sectionTitle">💡 提案のコツ</div><div class="grid">${tile('📝','メモ中心','Pencil（USB-C）でも使いやすい','accessory','blue')}${tile('🎨','描画をしっかり','Pencil Pro対応のAir / Proが候補','accessory','purple')}${tile('⌨️','文章入力が多い','キーボード込みの総予算で比較','accessory','green')}</div>`}
let diag={step:0,answers:{}};
const qs=[{q:'主な使い方は？',key:'use',opts:[['basic','動画・Web・学習'],['work','仕事・資料作成'],['creative','イラスト・動画編集']]},{q:'何を重視しますか？',key:'priority',opts:[['price','価格を抑えたい'],['balance','バランス'],['power','性能を最優先']]},{q:'Apple Pencilは？',key:'pencil',opts:[['light','メモ程度'],['pro','しっかり描きたい'],['none','ほぼ使わない']]},{q:'長く使う時の余裕は？',key:'years',opts:[['normal','普段使いで十分'],['long','長く快適に使いたい'],['max','高負荷でも長く使いたい']]}];
function diagnosis(){return `<img class="pageVisual slimVisual" src="ipad-lineup.svg" alt="おすすめ診断のiPadラインナップ"><div id="diagMount"></div>`}
function initDiagnosis(){diag={step:0,answers:{}};drawDiag()}
function drawDiag(){const m=document.querySelector('#diagMount');if(!m)return;if(diag.step>=qs.length){m.innerHTML=diagResult();return}const q=qs[diag.step];m.innerHTML=`<div class="sectionTitle">🎯 おすすめ診断 <span class="pill">${diag.step+1} / ${qs.length}</span></div><div class="progress"><i style="width:${(diag.step/qs.length)*100}%"></i></div><div class="card"><h2>${q.q}</h2><div class="choiceGrid">${q.opts.map(o=>`<button class="choice" data-v="${o[0]}">${o[1]}</button>`).join('')}</div></div>`;m.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{diag.answers[q.key]=b.dataset.v;diag.step++;drawDiag()})}
function diagResult(){let s={ipad:0,air:0,pro:0};const a=diag.answers;if(a.use==='basic')s.ipad+=4;if(a.use==='work')s.air+=4;if(a.use==='creative')s.pro+=4;if(a.priority==='price')s.ipad+=3;if(a.priority==='balance')s.air+=3;if(a.priority==='power')s.pro+=3;if(a.pencil==='pro'){s.air+=2;s.pro+=3}else if(a.pencil==='light')s.ipad+=2;if(a.years==='long')s.air+=3;if(a.years==='max')s.pro+=4;if(a.years==='normal')s.ipad+=1;const key=Object.keys(s).sort((x,y)=>s[y]-s[x])[0],m=models[key];const score=Math.min(99,82+s[key]*2);return `<div class="sectionTitle">✨ 診断結果</div><div class="resultHero"><span class="pill">あなたへのおすすめ</span><h1 style="color:${m.tone}">${m.name}</h1><div class="chip">${m.chip}</div><div class="score">${score}<small>/100</small></div><p>${m.for}</p></div><div class="sectionTitle">おすすめ理由</div><div class="card reasonList"><div class="reason"><b>①</b> 選んだ用途とのバランスが良い</div><div class="reason"><b>②</b> ${m.chip}チップで必要な性能に余裕を持たせやすい</div><div class="reason"><b>③</b> ${m.pencil}に対応</div></div><div class="actions"><button class="primary" onclick="go('talk')">この結果で接客トークを見る</button><button class="secondary" onclick="initDiagnosis()">診断をやり直す</button></div>`}
function talk(){return `<div class="sectionTitle">💬 お客様タイプ別 接客トーク</div>${talkOne('💰','価格重視のお客様','無印 iPad','「動画やネット、学習が中心でしたら、A16の無印iPadでも十分使いやすいです。必要以上に性能へ予算をかけず、容量やアクセサリに回す選び方もできます。」')}${talkOne('⚖️','迷っているお客様','iPad Air','「普段使いだけでなく、仕事や趣味まで広げるならAirが一番バランスを取りやすいです。M4なので余裕があり、Apple Pencil Proにも対応しています。」')}${talkOne('🎨','制作重視のお客様','iPad Pro','「イラストや動画編集を本格的にするならProが候補です。M5とProMotion対応ディスプレイで、処理性能だけでなく画面操作の滑らかさも強みです。」')}<div class="card"><b>提案の順番</b><div class="reasonList"><div class="reason">1️⃣ 使い方を聞く</div><div class="reason">2️⃣ 価格と性能の優先順位を確認</div><div class="reason">3️⃣ Pencil・キーボードの使用有無</div><div class="reason">4️⃣ 容量まで含めて1台に絞る</div></div></div>`}
function talkOne(icon,type,model,text){return `<article class="card talkCard" style="margin-bottom:12px"><div class="avatar">${icon}</div><div><span class="tag">${type}</span><span class="tag">${model}</span><div class="bubble">${text}</div></div></article>`}
function faq(){return `<div class="sectionTitle">❓ FAQ</div><div class="faq">${faqOne('無印 iPadで十分？','動画視聴、Web、学習、軽い資料作成などが中心なら十分候補になります。長く高負荷で使う、Apple Pencil Proを使いたい場合はAir以上も比較します。')}${faqOne('AirとProの一番大きな違いは？','性能だけでなくディスプレイも大きな違いです。ProはM5に加えてUltra Retina XDRとProMotionを備え、制作や滑らかな表示を重視する方向けです。')}${faqOne('容量は256GBが無難？','使い方によります。クラウド中心で動画を大量保存しないなら128GBも候補です。写真・動画・アプリが増えそうなら256GB以上が安心です。')}${faqOne('Wi‑FiとCellularはどちら？','自宅や職場のWi‑Fi中心ならWi‑Fiモデル。外出先で単体通信する機会が多いならCellularモデルも比較します。')}${faqOne('Apple Pencil Proを使えるのは？','現行のiPad Air（M4）とiPad Pro（M5）はApple Pencil Proに対応。無印iPad（A16）はApple Pencil（USB-C）と第1世代に対応します。')}</div>`}
function faqOne(q,a){return `<details><summary>${q}</summary><p>${a}</p></details>`}
const quiz=[{q:'無印iPad（A16）が対応するApple Pencilは？',opts:['Apple Pencil Proのみ','Apple Pencil（USB-C）と第1世代','第2世代のみ'],a:1},{q:'iPad Air（M4）の容量構成に含まれないものは？',opts:['128GB','1TB','2TB'],a:2},{q:'iPad Pro（M5）のディスプレイの特徴は？',opts:['Ultra Retina XDR / ProMotion','sRGBのみ','Retina HD'],a:0},{q:'迷ったお客様にまず確認したいのは？',opts:['好きな色だけ','使い方と優先順位','ケースの色'],a:1},{q:'無印・Air・Proの中でApple Pencil Pro対応は？',opts:['AirとPro','無印だけ','3機種すべて'],a:0}];let qi=0,score=0;
function learn(){return `<div id="quizMount"></div>`}function initQuiz(){qi=0;score=0;drawQuiz()}function drawQuiz(){const m=document.querySelector('#quizMount');if(!m)return;if(qi>=quiz.length){m.innerHTML=`<div class="resultHero"><h1>ミニテスト完了</h1><div class="score">${score}/${quiz.length}</div><p>${score===5?'全問正解！':score>=4?'かなり定着しています。':'比較ページを見直すとさらに強くなります。'}</p><button class="primary" onclick="initQuiz()">もう一度挑戦</button></div>`;return}const q=quiz[qi];m.innerHTML=`<div class="sectionTitle">🎓 ミニテスト <span class="pill">${qi+1}/${quiz.length}</span></div><div class="card"><div class="quizQ">${q.q}</div>${q.opts.map((o,i)=>`<button class="quizOpt" data-i="${i}">${String.fromCharCode(65+i)}. ${o}</button>`).join('')}<div id="explain" class="note"></div></div>`;m.querySelectorAll('.quizOpt').forEach(b=>b.onclick=()=>{const i=+b.dataset.i;if(i===q.a){b.classList.add('correct');score++;document.querySelector('#explain').textContent='⭕ 正解';}else{b.classList.add('wrong');m.querySelector(`.quizOpt[data-i="${q.a}"]`).classList.add('correct');document.querySelector('#explain').textContent='❌ 正解を確認して次へ';}m.querySelectorAll('.quizOpt').forEach(x=>x.disabled=true);setTimeout(()=>{qi++;drawQuiz()},650)})}
go('home',false);
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}))}

// build: Ver.1.1.2
